# This will be used if no other config file
# is specified.

tax-year = 2019
broker   = "TD Ameritrade"
map      = "map-td2irs-2019"

# Mapping from TD Ameritrade export csv file
# to the IRS transaction class.
#   key:   transaction class attr name
#   value: csv column name
[map-td2irs-2019]
Descrip = "?"
...




