=begin pod

=head1 NAME

TXF - Provides tools to create TXF files for import into tax software

=head1 SYNOPSIS

=begin code :lang<raku>
$ zef install TXF
...
$ csv2txf in=/path/file.cvs out=/path/to/file.txf
Normal end.
See new file /path/to/file.txf
$ txt2cvs in=/path/file2.txf out=/path/to/file2.csv
Normal end.
See new file /path/to/file2.cvs
=end code

=head1 DESCRIPTION

TXF is a module that provides Raku programs to convert
text files from/to CVS/TXF format. TXF files can be
used to import US IRS-required data on stock sales into
such tax software as I<TurboTax> and I<H&R Block>.

There are example account stock sale CVS output files from financial 
investment company
I<TD Ameritrade>, but the conversion programs should be able to
handle any input format if the user can provide a text input file
that maps the appropriate CVS file's field names (column headers)
to the standard IRS Form 8949 fields as used in the sample
I<Form8949.csv> and I<Form8949.xlsx> files.

=head1 CREDITS

=item Thanks to fellow [GnuCash](https://gnucash.org) user B<John John Ralls> <jralls@ceridwen.us> who kindly
found the included reference documents detailing the TXF file format specification.

=item Thanks to Github user B<Misha Brukman> and the Github repository
atn[https://github.com/mbrukman/csv2txf/](https://github.com/mbrukman/csv2txf/)
for inspiration and some code (as well as the name of the driver program C<cvs2txf.raku>).
See the code source in file C<./lib/TXF/CVS2TXT.rakumod>

=head1 AUTHOR

Tom Browder <tom.browder@cpan.org>

=head1 COPYRIGHT AND LICENSE

Copyright &#x00A9; 2020 Tom Browder

This library is free software; you can redistribute it or modify it under the Artistic License 2.0.

head1 Additional LICENSE

One file is licensed under the Apache-2.0 license:

=item ./lib/TXF/CVS2TXF.rakumod

A copy of that license is found in directory C<lib/TXF/>.

The original source of the content of that file came from
Github repository [https://github.com/mbrukman/csv2txf](https://github.com/mbrukman/csv2txf)
and was converted to its present form from Python to Raku.

=end pod
